[2021-07-22 19:04:50,919] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:04:58,838] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22935
[2021-07-22 19:04:59,824] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:04:59,825] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5020
[2021-07-22 19:05:06,555] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:05:06,556] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5020
[2021-07-22 19:05:07,140] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:05:07,141] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5020
[2021-07-22 19:05:07,746] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:05:07,747] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5020
[2021-07-22 19:05:08,355] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:05:08,356] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5020
[2021-07-22 19:05:08,677] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/MiracleNumber/ HTTP/1.1" 200 14172
[2021-07-22 19:05:08,777] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/bootstrap/css/bootstrap.css HTTP/1.1" 200 209709
[2021-07-22 19:05:08,819] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/popper/popper.js HTTP/1.1" 200 69253
[2021-07-22 19:05:08,851] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/bootstrap/js/bootstrap.js HTTP/1.1" 200 148340
[2021-07-22 19:05:08,866] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/jquery/jquery-3.6.0.min.js HTTP/1.1" 200 89503
[2021-07-22 19:09:49,194] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\templates\base.html changed, reloading.
[2021-07-22 19:09:51,186] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:14:58,197] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\templates\base.html changed, reloading.
[2021-07-22 19:15:00,090] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:21:17,874] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\filters.py changed, reloading.
[2021-07-22 19:21:19,695] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:31:15,655] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-07-22 19:31:17,530] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:31:27,395] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:31:27,396] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:31:27,970] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:31:27,971] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:31:28,570] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:31:28,571] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:31:29,177] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:31:29,178] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:31:29,786] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:31:29,786] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:31:30,387] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:31:30,388] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:31:30,767] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Contacts HTTP/1.1" 301 0
[2021-07-22 19:31:32,275] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 7, in Contacts_search
    f = ContactsFilter(request.GET,queryset=Contacts.objects.filter(Status = '可选').order_by('Stars'))
  File "E:\DRF\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1284, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1110, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1537, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'Status' into field. Choices are: Email, Memo, Mobile, Name, Organize, Organize_id, contacthistory, id
[2021-07-22 19:31:32,278] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/ HTTP/1.1" 500 116084
[2021-07-22 19:34:25,919] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 7, in Contacts_search
    f = ContactsFilter(request.GET,queryset=Contacts.objects.filter(Status = '可选').order_by('Stars'))
  File "E:\DRF\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1284, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1110, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1537, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'Status' into field. Choices are: Email, Memo, Mobile, Name, Organize, Organize_id, contacthistory, id
[2021-07-22 19:34:25,922] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/ HTTP/1.1" 500 116221
[2021-07-22 19:34:33,922] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:34:34,994] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22935
[2021-07-22 19:34:39,441] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:39,441] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:40,036] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:40,037] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:40,637] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:40,637] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:41,237] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:41,238] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:41,861] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:41,862] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:42,468] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:42,470] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:43,074] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:43,074] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:43,685] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:43,686] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:44,286] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:34:44,286] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:34:45,526] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 7, in Contacts_search
    f = ContactsFilter(request.GET,queryset=Contacts.objects.filter(Status = '可选').order_by('Stars'))
  File "E:\DRF\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1284, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1110, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1537, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'Status' into field. Choices are: Email, Memo, Mobile, Name, Organize, Organize_id, contacthistory, id
[2021-07-22 19:34:45,531] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/ HTTP/1.1" 500 116478
[2021-07-22 19:35:31,570] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-22 19:35:33,486] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:35:36,406] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Contacts/ HTTP/1.1" 200 13502
[2021-07-22 19:36:06,524] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\filters.py changed, reloading.
[2021-07-22 19:36:08,414] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:36:09,493] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Contacts/ HTTP/1.1" 200 13361
[2021-07-22 19:36:26,254] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 8, in Contacts_search
    paginator = Paginator(f.qs, 20)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "E:\DRF\venv\lib\site-packages\django_filters\filters.py", line 146, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1182, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
[2021-07-22 19:36:26,257] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/?Organize=&Number=%E5%B8%85%E6%99%AE&Name=&Mobile=&Email=&Memo= HTTP/1.1" 500 125792
[2021-07-22 19:36:39,707] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 8, in Contacts_search
    paginator = Paginator(f.qs, 20)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "E:\DRF\venv\lib\site-packages\django_filters\filters.py", line 146, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1182, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
[2021-07-22 19:36:39,710] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/?Organize=%E5%B8%85%E6%99%AE&Number=&Name=&Mobile=&Email=&Memo= HTTP/1.1" 500 125794
[2021-07-22 19:36:51,675] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 8, in Contacts_search
    paginator = Paginator(f.qs, 20)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "E:\DRF\venv\lib\site-packages\django_filters\filters.py", line 146, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1182, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains
[2021-07-22 19:36:51,678] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/?Organize=%E5%B8%85%E6%99%AE&Number=&Name=%E7%99%BD%E6%97%AD&Mobile=&Email=&Memo= HTTP/1.1" 500 125908
[2021-07-22 19:37:11,833] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\filters.py changed, reloading.
[2021-07-22 19:37:13,745] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:37:19,082] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '帅普'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 8, in Contacts_search
    paginator = Paginator(f.qs, 20)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "E:\DRF\venv\lib\site-packages\django_filters\filters.py", line 146, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\DRF\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '帅普'.
[2021-07-22 19:37:19,087] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/?Organize=%E5%B8%85%E6%99%AE&Number=&Name=%E7%99%BD%E6%97%AD&Mobile=&Email=&Memo= HTTP/1.1" 500 142708
[2021-07-22 19:37:32,326] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Contacts/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1823, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '帅普'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 8, in Contacts_search
    paginator = Paginator(f.qs, 20)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 243, in qs
    qs = self.filter_queryset(qs)
  File "E:\DRF\venv\lib\site-packages\django_filters\filterset.py", line 230, in filter_queryset
    queryset = self.filters[name].filter(queryset, value)
  File "E:\DRF\venv\lib\site-packages\django_filters\filters.py", line 146, in filter
    qs = self.get_method(qs)(**{lookup: value})
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\query.py", line 1191, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\DRF\venv\lib\site-packages\django\db\models\fields\related_lookups.py", line 117, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\fields\__init__.py", line 1825, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '帅普'.
[2021-07-22 19:37:32,329] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Contacts/?Organize=&Number=%E5%B8%85%E6%99%AE&Name=%E7%99%BD%E6%97%AD&Mobile=&Email=&Memo= HTTP/1.1" 500 142569
[2021-07-22 19:37:42,322] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\filters.py changed, reloading.
[2021-07-22 19:37:44,352] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:37:48,118] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22935
[2021-07-22 19:37:54,031] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Contacts/?Organize=&Number=&Name=%E7%99%BD%E6%97%AD&Mobile=&Email=&Memo= HTTP/1.1" 200 7211
[2021-07-22 19:38:07,529] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:38:07,530] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5157
[2021-07-22 19:38:08,036] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin HTTP/1.1" 301 0
[2021-07-22 19:38:08,307] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22935
[2021-07-22 19:38:12,516] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59296
[2021-07-22 19:38:12,529] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css?_=2.7 HTTP/1.1" 304 0
[2021-07-22 19:38:12,539] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css?_=20180905 HTTP/1.1" 304 0
[2021-07-22 19:38:12,546] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,547] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css?_=20180905 HTTP/1.1" 304 0
[2021-07-22 19:38:12,547] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,548] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,557] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,600] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 304 0
[2021-07-22 19:38:12,601] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2021-07-22 19:38:12,678] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:38:12,820] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[2021-07-22 19:38:12,876] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[2021-07-22 19:38:21,240] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/1/change/ HTTP/1.1" 200 20841
[2021-07-22 19:38:21,265] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 304 0
[2021-07-22 19:38:21,269] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/select2/select2.full.js HTTP/1.1" 200 173566
[2021-07-22 19:38:21,289] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/autocomplete.css HTTP/1.1" 200 9114
[2021-07-22 19:38:21,290] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/vendor/select2/select2.css HTTP/1.1" 200 17358
[2021-07-22 19:38:21,300] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/autocomplete.js HTTP/1.1" 200 1320
[2021-07-22 19:38:21,312] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
[2021-07-22 19:38:21,322] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 304 0
[2021-07-22 19:38:21,325] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 304 0
[2021-07-22 19:38:21,333] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2021-07-22 19:38:21,341] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2021-07-22 19:38:21,438] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:38:28,237] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/contacts/1/change/ HTTP/1.1" 200 21172
[2021-07-22 19:38:28,409] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:41:05,476] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:41:06,659] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22935
[2021-07-22 19:41:15,063] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacthistory/ HTTP/1.1" 200 55547
[2021-07-22 19:41:15,232] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:41:16,326] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59296
[2021-07-22 19:41:16,482] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:41:19,184] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/1/change/ HTTP/1.1" 200 20841
[2021-07-22 19:41:19,349] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:41:27,489] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/contacts/1/change/ HTTP/1.1" 200 21172
[2021-07-22 19:41:27,661] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:41:58,274] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 19:42:00,218] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:42:37,299] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22935
[2021-07-22 19:42:37,821] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59296
[2021-07-22 19:42:37,971] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:42:40,109] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/1/change/ HTTP/1.1" 200 20851
[2021-07-22 19:42:40,305] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:42:54,556] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/contacts/1/change/ HTTP/1.1" 302 0
[2021-07-22 19:42:54,960] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59671
[2021-07-22 19:42:55,114] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:43:02,453] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Contacts/?Name=&Mobile=&Email=&Memo= HTTP/1.1" 200 12581
[2021-07-22 19:43:04,590] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 19:44:34,367] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /Miracle/MiracleNumber/ HTTP/1.1" 200 17260
[2021-07-22 19:48:50,943] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\filters.py changed, reloading.
[2021-07-22 19:48:52,777] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:48:57,050] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\filters.py changed, reloading.
[2021-07-22 19:48:58,874] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:49:11,285] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\filters.py changed, reloading.
[2021-07-22 19:49:13,151] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:50:12,917] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-22 19:50:14,703] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:50:34,223] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-22 19:50:36,013] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:51:01,627] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\djangoProject\urls.py changed, reloading.
[2021-07-22 19:51:03,452] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:51:15,901] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:51:15,901] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 19:51:16,487] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:51:16,487] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 19:51:17,090] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:51:17,090] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 19:51:17,703] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:51:17,704] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 19:51:18,304] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:51:18,304] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 19:51:18,919] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 19:51:18,920] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 19:51:19,270] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/ HTTP/1.1" 200 6654
[2021-07-22 19:52:54,419] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/ HTTP/1.1" 200 6629
[2021-07-22 19:53:21,195] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-22 19:53:23,061] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:53:23,995] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Oblist/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 16, in Oblist_search
    f = OblistFilter(request.GET,queryset=Oblist.objects.all())
NameError: name 'OblistFilter' is not defined
[2021-07-22 19:53:23,997] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Oblist/ HTTP/1.1" 500 70746
[2021-07-22 19:53:45,224] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-22 19:53:47,048] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:53:47,710] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/ HTTP/1.1" 200 7019
[2021-07-22 19:55:25,000] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 19:55:26,803] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:56:18,243] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 19:56:20,210] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 19:56:48,132] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/ HTTP/1.1" 200 7019
[2021-07-22 19:56:51,560] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23217
[2021-07-22 19:56:52,154] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59453
[2021-07-22 19:56:52,309] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:56:54,071] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 34691
[2021-07-22 19:56:54,218] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:56:57,024] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/add/ HTTP/1.1" 200 18836
[2021-07-22 19:56:57,176] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:57:22,788] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/add/ HTTP/1.1" 302 0
[2021-07-22 19:57:23,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 35143
[2021-07-22 19:57:23,371] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 19:57:26,961] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/ HTTP/1.1" 200 7604
[2021-07-22 19:57:29,284] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 19:57:46,874] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 7616
[2021-07-22 20:03:05,407] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:03:07,250] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:03:11,159] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 20:03:11,709] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 35003
[2021-07-22 20:03:11,857] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 20:03:15,824] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59453
[2021-07-22 20:03:15,963] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 20:03:17,216] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 35003
[2021-07-22 20:03:17,366] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 20:03:31,830] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:03:33,855] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:03:48,390] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 7616
[2021-07-22 20:04:13,292] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:04:15,394] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:04:55,423] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:04:57,291] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:05:03,741] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 7616
[2021-07-22 20:08:16,031] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 20:08:18,026] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:08:22,697] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/Oblist/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "E:\DRF\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "E:\DRF\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "E:\DRF\venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "E:\DRF\venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'crm_oblist.Campaign' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 22, in Oblist_search
    return render(request,'Oblist_filter.html',context)
  File "E:\DRF\venv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\DRF\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\DRF\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\defaulttags.py", line 168, in render
    len_values = len(values)
  File "E:\DRF\venv\lib\site-packages\django\core\paginator.py", line 177, in __len__
    return len(self.object_list)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\utils.py", line 98, in execute
    return super().execute(sql, params)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\DRF\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\DRF\venv\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\mysql\base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "E:\DRF\venv\lib\site-packages\pymysql\cursors.py", line 148, in execute
    result = self._query(query)
  File "E:\DRF\venv\lib\site-packages\pymysql\cursors.py", line 310, in _query
    conn.query(q)
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 775, in _read_query_result
    result.read()
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "E:\DRF\venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "E:\DRF\venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.OperationalError: (1054, "Unknown column 'crm_oblist.Campaign' in 'field list'")
[2021-07-22 20:08:22,720] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 500 292115
[2021-07-22 20:09:24,318] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:09:26,119] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:10:01,006] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:10:02,910] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:10:12,605] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 7719
[2021-07-22 20:13:57,107] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:13:58,901] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:32:02,462] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 20:32:04,386] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 20:34:32,238] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 7719
[2021-07-22 20:34:34,944] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 7719
[2021-07-22 20:34:35,928] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 7719
[2021-07-22 20:35:29,517] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=%E6%B2%88&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 8404
[2021-07-22 20:35:39,954] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 25748
[2021-07-22 20:37:59,196] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 25759
[2021-07-22 20:38:49,424] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?Name=&Phone1=&Phone2=&Status=&Memo= HTTP/1.1" 200 25791
[2021-07-22 20:39:10,558] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=2 HTTP/1.1" 200 25745
[2021-07-22 20:39:18,184] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=3 HTTP/1.1" 200 25727
[2021-07-22 20:39:23,780] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=4 HTTP/1.1" 200 25864
[2021-07-22 20:39:26,047] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=5 HTTP/1.1" 200 25724
[2021-07-22 20:39:28,190] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=6 HTTP/1.1" 200 25601
[2021-07-22 20:40:48,334] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=7 HTTP/1.1" 200 25604
[2021-07-22 20:40:50,791] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=8 HTTP/1.1" 200 25525
[2021-07-22 20:40:58,834] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 20:41:18,384] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/Oblist/?page=36 HTTP/1.1" 200 24397
[2021-07-22 21:02:56,717] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:02:59,067] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:06:22,274] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:06:24,317] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:11:08,311] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:11:10,602] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:11:23,408] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:11:23,917] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 62932)

[2021-07-22 21:11:24,314] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 361327
[2021-07-22 21:11:24,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:12:13,203] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:12:15,275] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:12:19,267] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:12:20,041] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:12:20,198] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:12:23,661] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:12:23,814] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:12:26,500] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:12:26,666] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:12:29,412] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:12:29,584] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:12:33,707] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/js/axios.min.map HTTP/1.1" 200 117473
[2021-07-22 21:12:33,724] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/waves/waves.min.js.map HTTP/1.1" 200 9739
[2021-07-22 21:12:33,742] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/index.css.map HTTP/1.1" 200 3250
[2021-07-22 21:12:33,748] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/css/base.css.map HTTP/1.1" 200 1511
[2021-07-22 21:12:33,748] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/simpleui-x/theme/simpleui.css.map HTTP/1.1" 200 1935
[2021-07-22 21:12:43,202] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:12:43,365] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:13:52,714] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:13:54,686] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:13:59,032] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:13:59,908] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:14:00,069] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:14:02,698] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:14:02,853] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:14:06,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:14:06,358] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:14:31,626] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370865
[2021-07-22 21:14:31,792] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:15:51,031] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:15:53,174] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:15:57,581] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:15:58,433] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 370863
[2021-07-22 21:15:58,593] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:16:05,480] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370863
[2021-07-22 21:16:05,647] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:16:25,316] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:16:27,508] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:16:29,963] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:16:30,827] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 370863
[2021-07-22 21:16:30,988] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:16:33,445] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 370863
[2021-07-22 21:16:33,617] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:20:47,148] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:20:49,065] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:22:09,009] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:22:11,422] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:22:15,774] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:22:24,522] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 375963
[2021-07-22 21:22:24,684] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:24:26,525] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:24:28,508] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:24:31,226] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:24:39,316] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 375963
[2021-07-22 21:24:39,463] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:27:14,770] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:27:16,942] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:28:44,517] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:28:46,730] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:29:04,148] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:29:06,343] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:29:09,356] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:29:11,493] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:29:18,130] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:29:20,170] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:29:32,602] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:29:34,618] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:29:58,779] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:30:00,915] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:32:21,773] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:32:22,878] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:32:27,552] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:32:28,697] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:32:32,353] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:32:34,336] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:32:36,288] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:32:38,394] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:32:50,904] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:32:52,979] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:33:14,791] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:33:16,575] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:34:15,549] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:34:17,518] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:34:45,165] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:34:47,337] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:35:06,818] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:35:07,553] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 371665
[2021-07-22 21:35:07,704] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:35:10,784] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /makecall/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 41, in makecall
    return HttpResponse(html)
UnboundLocalError: local variable 'html' referenced before assignment
[2021-07-22 21:35:10,786] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /makecall/ HTTP/1.1" 500 70754
[2021-07-22 21:41:13,116] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 21:41:14,995] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:41:29,256] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 21:41:31,252] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:41:37,666] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 371665
[2021-07-22 21:41:40,731] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /makecall/ HTTP/1.1" 200 58
[2021-07-22 21:42:03,484] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 371665
[2021-07-22 21:42:06,005] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /makecall/ HTTP/1.1" 200 106
[2021-07-22 21:42:23,620] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 371665
[2021-07-22 21:45:32,148] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:45:34,124] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:45:41,504] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:45:42,172] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'makecall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "E:\DRF\venv\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Oblist has no field named 'makecall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "E:\DRF\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\DRF\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "E:\DRF\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in result_list
    'results': list(results(cl)),
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 284, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 275, in __init__
    super().__init__(*items)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 200, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 274, in lookup_field
    value = attr(obj)
  File "E:\djangoProject\crm\admin.py", line 58, in makecall
    html = html + self.Phone1
AttributeError: 'OblistAdmin' object has no attribute 'Phone1'
[2021-07-22 21:45:42,177] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /admin/crm/oblist/ HTTP/1.1" 500 385358
[2021-07-22 21:46:17,065] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\models.py changed, reloading.
[2021-07-22 21:46:18,934] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:46:22,296] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:46:22,944] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'makecall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "E:\DRF\venv\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Oblist has no field named 'makecall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "E:\DRF\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\DRF\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "E:\DRF\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in result_list
    'results': list(results(cl)),
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 284, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 275, in __init__
    super().__init__(*items)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 200, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 278, in lookup_field
    value = attr()
TypeError: makecall() missing 1 required positional argument: 'obj'
[2021-07-22 21:46:22,951] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /admin/crm/oblist/ HTTP/1.1" 500 381181
[2021-07-22 21:46:57,913] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:46:59,813] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:48:59,455] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:49:00,135] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/crm/oblist/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\db\models\options.py", line 608, in get_field
    return self.fields_map[field_name]
KeyError: 'makecall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 265, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 296, in _get_non_gfk_field
    field = opts.get_field(name)
  File "E:\DRF\venv\lib\site-packages\django\db\models\options.py", line 610, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Oblist has no field named 'makecall'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "E:\DRF\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\DRF\venv\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "E:\DRF\venv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "E:\DRF\venv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\base.py", line 33, in render
    return super().render(context)
  File "E:\DRF\venv\lib\site-packages\django\template\library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 308, in result_list
    'results': list(results(cl)),
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 284, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 275, in __init__
    super().__init__(*items)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 200, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\utils.py", line 274, in lookup_field
    value = attr(obj)
  File "E:\djangoProject\crm\admin.py", line 58, in makecall
    html = html + self.Phone1
AttributeError: 'OblistAdmin' object has no attribute 'Phone1'
[2021-07-22 21:49:00,158] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /admin/crm/oblist/ HTTP/1.1" 500 386380
[2021-07-22 21:51:10,952] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:51:12,752] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:51:18,223] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:51:18,990] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 21:51:19,152] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:51:21,334] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 200 106
[2021-07-22 21:51:38,590] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 21:52:47,347] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 21:52:49,427] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:53:21,961] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 21:53:23,856] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:53:26,665] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:53:27,503] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 21:53:27,652] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:53:36,759] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /makecall/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'destNumber'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 33, in makecall
    data["destNumber"]=str(req.POST["destNumber"]).replace("\n","")
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'destNumber'
[2021-07-22 21:53:36,761] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /makecall/?destNumber=13817560641 HTTP/1.1" 500 80316
[2021-07-22 21:54:32,368] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 21:54:34,201] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:54:37,640] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:54:38,395] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 21:54:38,552] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:54:42,946] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 200 74
[2021-07-22 21:54:51,797] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 21:57:25,964] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:57:27,889] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:57:35,960] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:57:36,701] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 372765
[2021-07-22 21:57:36,836] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:57:40,993] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/makecall(18017585688) HTTP/1.1" 301 0
[2021-07-22 21:57:41,152] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/makecall(18017585688)/ HTTP/1.1" 302 0
[2021-07-22 21:57:41,344] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/makecall(18017585688)/change/ HTTP/1.1" 302 0
[2021-07-22 21:57:41,583] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:57:41,915] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:57:42,607] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 372928
[2021-07-22 21:57:42,761] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:58:06,951] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 21:58:08,938] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 21:58:11,583] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 21:58:12,346] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 21:58:12,506] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 21:58:24,228] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /makecall/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'destNumber'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 33, in makecall
    data["destNumber"]=str(req.POST["destNumber"]).replace("\n","")
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'destNumber'
[2021-07-22 21:58:24,230] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 500 80151
[2021-07-22 22:00:09,079] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 22:00:10,990] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:00:19,389] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 22:00:23,036] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:00:23,767] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 22:00:23,918] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:00:26,808] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /makecall/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 33, in makecall
    data["destNumber"]=str(req.POST.get(["destNumber"])).replace("\n","")
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 116, in get
    val = self[key]
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
TypeError: unhashable type: 'list'
[2021-07-22 22:00:26,810] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 500 79737
[2021-07-22 22:00:40,976] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 22:00:42,932] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:00:49,183] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 22:00:51,106] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:00:57,127] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 22:01:00,130] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:01:00,870] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 22:01:01,008] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:01:05,593] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /makecall/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'destNumber'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 33, in makecall
    data["destNumber"]=str(req.POST["destNumber"]).replace("\n","")
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'destNumber'
[2021-07-22 22:01:05,594] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 500 80151
[2021-07-22 22:01:15,137] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:15,138] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:15,721] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:15,722] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:16,340] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:16,340] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:16,954] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:16,954] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:27,744] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:27,745] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:28,352] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:28,353] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:28,955] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:28,956] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:29,557] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:29,557] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:30,156] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:30,157] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:30,756] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:30,757] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:31,376] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:31,376] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:31,987] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:31,988] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:32,587] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-22 22:01:32,588] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5290
[2021-07-22 22:01:42,910] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /makecall/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'destNumber'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 33, in makecall
    data["destNumber"]=str(req.POST["destNumber"]).replace("\n","")
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'destNumber'
[2021-07-22 22:01:42,912] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /makecall/?destNumber=%E2%80%9C18017585688%E2%80%9D HTTP/1.1" 500 80131
[2021-07-22 22:08:17,224] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 22:08:19,461] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:08:40,121] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 371665
[2021-07-22 22:08:44,545] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /makecall/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'destNumber'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\Miracle\views.py", line 33, in makecall
    data["destNumber"]=str(req.POST["destNumber"]).replace("\n","")
  File "E:\DRF\venv\lib\site-packages\django\utils\datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'destNumber'
[2021-07-22 22:08:44,548] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /makecall/ HTTP/1.1" 500 79547
[2021-07-22 22:12:31,771] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 22:12:33,637] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:12:56,942] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 22:12:59,104] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:13:04,552] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:13:05,366] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 22:13:05,519] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:13:09,334] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 200 106
[2021-07-22 22:13:17,615] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373965
[2021-07-22 22:21:50,353] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 22:21:52,296] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:21:58,115] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:21:58,935] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373969
[2021-07-22 22:21:59,103] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:27:03,514] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 200 106
[2021-07-22 22:27:19,256] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 373969
[2021-07-22 22:28:23,667] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 22:28:25,540] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:28:30,242] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:28:31,059] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 375469
[2021-07-22 22:28:31,209] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:28:34,055] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /makecall/?destNumber=18017585688 HTTP/1.1" 200 106
[2021-07-22 22:32:39,825] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 22:32:42,120] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:37:11,322] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 22:37:13,165] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:37:16,302] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 22:37:18,672] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:37:24,437] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:37:25,294] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:37:25,307] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1463
[2021-07-22 22:37:25,476] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:37:27,879] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:37:27,879] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:37:30,176] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:37:30,205] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:37:30,358] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:40:02,512] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:40:03,248] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:40:03,260] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1488
[2021-07-22 22:40:03,410] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:40:05,700] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:40:05,700] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:40:09,344] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:40:09,362] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:40:09,517] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:41:16,490] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 22:41:18,327] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:41:24,158] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:41:24,949] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:41:24,967] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:41:25,106] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:41:27,070] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:41:27,071] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:41:30,486] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:41:40,953] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /admin/jsi18n/
Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 233, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 613, in connect
    sock = socket.create_connection(
  File "D:\Python39\lib\socket.py", line 843, in create_connection
    raise err
  File "D:\Python39\lib\socket.py", line 831, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\db\backends\base\base.py", line 219, in ensure_connection
    self.connect()
  File "E:\DRF\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\base\base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "E:\DRF\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\mysql\base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 664, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'sz001.ezphone.cn' (timed out)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "E:\DRF\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\sites.py", line 250, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\sites.py", line 221, in inner
    if not self.has_permission(request):
  File "E:\DRF\venv\lib\site-packages\django\contrib\admin\sites.py", line 195, in has_permission
    return request.user.is_active and request.user.is_staff
  File "E:\DRF\venv\lib\site-packages\django\utils\functional.py", line 246, in inner
    self._setup()
  File "E:\DRF\venv\lib\site-packages\django\utils\functional.py", line 382, in _setup
    self._wrapped = self._setupfunc()
  File "E:\DRF\venv\lib\site-packages\django\contrib\auth\middleware.py", line 23, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "E:\DRF\venv\lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "E:\DRF\venv\lib\site-packages\django\contrib\auth\__init__.py", line 177, in get_user
    user_id = _get_user_session_key(request)
  File "E:\DRF\venv\lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "E:\DRF\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 65, in __getitem__
    return self._session[key]
  File "E:\DRF\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 238, in _get_session
    self._session_cache = self.load()
  File "E:\DRF\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 43, in load
    s = self._get_session_from_db()
  File "E:\DRF\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "E:\DRF\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 431, in get
    num = len(clone)
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 262, in __len__
    self._fetch_all()
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 1324, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "E:\DRF\venv\lib\site-packages\django\db\models\query.py", line 51, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "E:\DRF\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1173, in execute_sql
    cursor = self.connection.cursor()
  File "E:\DRF\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\base\base.py", line 259, in cursor
    return self._cursor()
  File "E:\DRF\venv\lib\site-packages\django\db\backends\base\base.py", line 235, in _cursor
    self.ensure_connection()
  File "E:\DRF\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\base\base.py", line 219, in ensure_connection
    self.connect()
  File "E:\DRF\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\DRF\venv\lib\site-packages\django\db\backends\base\base.py", line 219, in ensure_connection
    self.connect()
  File "E:\DRF\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\base\base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "E:\DRF\venv\lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "E:\DRF\venv\lib\site-packages\django\db\backends\mysql\base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 353, in __init__
    self.connect()
  File "E:\DRF\venv\lib\site-packages\pymysql\connections.py", line 664, in connect
    raise exc
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'sz001.ezphone.cn' (timed out)")
[2021-07-22 22:41:40,961] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /admin/jsi18n/ HTTP/1.1" 500 285187
[2021-07-22 22:41:40,962] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 4433)

[2021-07-22 22:41:57,548] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 22:41:58,617] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:42:02,780] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:42:03,532] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:42:03,544] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:42:03,691] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:42:05,394] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:42:05,394] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:42:08,098] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:42:08,266] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:46:44,511] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:46:45,371] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:46:45,387] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1490
[2021-07-22 22:46:45,529] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:46:47,084] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:46:47,084] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:46:47,654] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:46:47,680] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:46:47,831] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:46:50,530] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:46:50,530] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:46:51,115] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:46:51,137] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:46:51,293] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:47:03,977] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:47:04,708] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:47:04,722] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1493
[2021-07-22 22:47:04,866] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:47:06,451] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:47:06,452] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:47:08,582] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:47:08,638] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:47:08,769] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:48:50,576] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:48:51,314] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:48:51,327] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1489
[2021-07-22 22:48:51,475] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:48:52,920] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:48:52,920] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:48:56,601] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:48:56,619] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:48:56,769] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:49:18,495] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:49:19,225] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:49:19,236] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1490
[2021-07-22 22:49:19,385] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:49:20,568] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:49:20,569] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:49:23,424] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:49:23,456] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:49:23,596] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:49:29,780] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:49:30,549] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:49:30,562] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:49:30,710] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:49:32,292] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:49:32,293] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:50:23,280] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:50:23,304] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1485
[2021-07-22 22:50:23,468] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:50:25,196] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:50:25,196] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:50:27,922] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:50:27,947] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:50:28,112] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:53:23,361] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:53:24,151] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:53:24,163] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1512
[2021-07-22 22:53:24,301] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:53:25,843] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:53:25,844] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:53:51,908] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:53:51,928] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:53:52,056] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:56:31,600] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:56:32,354] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:56:32,371] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1560
[2021-07-22 22:56:32,526] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:56:34,792] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:56:34,812] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:56:34,959] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:56:41,437] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:56:41,469] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:56:41,623] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:57:45,402] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:57:46,156] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:57:46,170] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1512
[2021-07-22 22:57:46,321] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:57:47,991] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:57:47,992] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:57:55,629] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:57:55,646] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:57:55,818] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:59:03,840] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 22:59:04,596] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:59:04,611] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1535
[2021-07-22 22:59:04,744] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 22:59:06,358] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 22:59:06,358] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 22:59:17,053] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 22:59:17,086] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 22:59:17,224] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:02:12,306] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 23:02:14,273] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:02:20,023] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23233
[2021-07-22 23:02:20,836] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 23:02:20,850] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:02:20,981] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:02:22,809] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 23:02:22,810] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 23:02:31,534] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 23:02:31,709] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:02:33,618] [log.py:224] [log:log_response] [WARNING]- Forbidden (CSRF token missing or incorrect.): /makecall/
[2021-07-22 23:02:33,618] [basehttp.py:161] [basehttp:log_message] [WARNING]- "POST /makecall/ HTTP/1.1" 403 2514
[2021-07-22 23:02:37,120] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 23:02:37,297] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:04:03,389] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:04:05,458] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:04:08,630] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 23:04:09,379] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374112
[2021-07-22 23:04:10,144] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:04:10,294] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:04:30,586] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/add/ HTTP/1.1" 200 19387
[2021-07-22 23:04:30,764] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:05:00,209] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/add/ HTTP/1.1" 302 0
[2021-07-22 23:05:00,751] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374973
[2021-07-22 23:05:00,767] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:05:00,904] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:05:04,026] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 23:05:04,553] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374824
[2021-07-22 23:05:05,981] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:05:46,242] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/719/change/ HTTP/1.1" 200 20072
[2021-07-22 23:05:46,266] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:05:46,417] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:05:54,345] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/719/change/ HTTP/1.1" 302 0
[2021-07-22 23:05:54,991] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 375118
[2021-07-22 23:05:55,155] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:06:01,521] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/?Status=%E6%9C%89%E6%84%8F%E5%90%91 HTTP/1.1" 200 286523
[2021-07-22 23:06:01,677] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:06:09,471] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/? HTTP/1.1" 200 374969
[2021-07-22 23:06:09,639] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:06:19,555] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/?Campaign=%E6%B5%8B%E8%AF%95 HTTP/1.1" 200 286454
[2021-07-22 23:06:19,729] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:06:29,878] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/? HTTP/1.1" 200 374969
[2021-07-22 23:06:29,904] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:06:30,059] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:10:29,284] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:10:31,215] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:12:39,629] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:12:41,810] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:13:29,154] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:13:31,572] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:14:08,010] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:14:09,971] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:14:36,940] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:14:38,888] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:16:04,473] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 23:16:06,728] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:17:50,288] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 23:17:52,523] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:20:41,834] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:20:43,871] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:21:07,509] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:21:09,465] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:21:18,386] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:21:20,488] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:21:58,683] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:22:00,706] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:22:56,479] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:22:58,638] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:23:20,497] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23219
[2021-07-22 23:23:21,313] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:23:21,325] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:23:21,466] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:23:23,171] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 5
[2021-07-22 23:23:23,692] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:23:28,600] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:23:57,758] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:23:59,879] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:24:01,685] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23219
[2021-07-22 23:24:02,491] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:24:02,645] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:24:04,092] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 23:24:04,656] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:24:08,617] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:25:19,168] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 23:25:21,304] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:25:31,632] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\admin.py changed, reloading.
[2021-07-22 23:25:33,627] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:25:36,869] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 23:25:37,736] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:25:38,130] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:26:45,428] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:26:47,541] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:26:50,916] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23219
[2021-07-22 23:26:51,732] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:26:51,746] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:26:51,881] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:26:53,803] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 23:26:54,270] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:26:55,195] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:28:59,096] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:29:01,205] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:29:28,244] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:29:30,315] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-22 23:33:33,217] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 58
[2021-07-22 23:33:33,842] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:33:34,896] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 200 1451
[2021-07-22 23:33:35,042] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:33:47,336] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 58
[2021-07-22 23:33:47,757] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:33:48,824] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:35:04,429] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/logout/ HTTP/1.1" 200 161
[2021-07-22 23:35:04,529] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/login/ HTTP/1.1" 200 4071
[2021-07-22 23:35:19,796] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/login/ HTTP/1.1" 200 4314
[2021-07-22 23:35:29,868] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/login/ HTTP/1.1" 302 0
[2021-07-22 23:35:30,207] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 22680
[2021-07-22 23:35:34,232] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:35:34,259] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-22 23:35:34,400] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:35:37,533] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /makecall/ HTTP/1.1" 200 106
[2021-07-22 23:35:37,949] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/crm/oblist/ HTTP/1.1" 200 374969
[2021-07-22 23:35:40,179] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-22 23:36:36,395] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\views.py changed, reloading.
[2021-07-22 23:36:38,465] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
